/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MlCallbackRouteImport } from './routes/ml-callback'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PromoRouteImport } from './routes/promo'

const MlCallbackRoute = MlCallbackRouteImport.update({
  id: '/ml-callback',
  path: '/ml-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PromoRoute = PromoRouteImport.update({
  id: '/promo',
  path: '/promo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ml-callback': typeof MlCallbackRoute
  '/promo': typeof PromoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ml-callback': typeof MlCallbackRoute
  '/promo': typeof PromoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ml-callback': typeof MlCallbackRoute
  '/promo': typeof PromoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ml-callback' | '/promo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ml-callback' | '/promo'
  id: '__root__' | '/' | '/ml-callback' | '/promo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MlCallbackRoute: typeof MlCallbackRoute
  PromoRoute: typeof PromoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ml-callback': {
      id: '/ml-callback'
      path: '/ml-callback'
      fullPath: '/ml-callback'
      preLoaderRoute: typeof MlCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promo': {
      id: '/promo'
      path: '/promo'
      fullPath: '/promo'
      preLoaderRoute: typeof PromoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MlCallbackRoute: MlCallbackRoute,
  PromoRoute: PromoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
